name: Base CI pipeline

on:
  push:
    branches:
      [master, develop]
  pull_request:
    branches:
      - master

jobs:
  format-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: |
          echo "Running Prettier to check for formatting issues..."
          npm run prettier:check

      - name: Run ESLint check
        run: |
          echo "Running ESLint to check for linting issues..."
          npm run lint 

      - name: Run TypeScript compile check
        run: |
          echo "Running TypeScript compiler to check for type issues..."
          npx tsc --noEmit

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yaml
          up-flags: -d

      - name: Run test for empty array scenario
        run: |
          echo "Running local API tests..."
          npx playwright test tests/EmptyArray.spec.ts

      - name: Run remaining tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Running rest API tests..."
          npx playwright test tests/GetAllUsers.spec.ts test tests/User.Api.spec.ts test tests/GetOrder.spec.ts test tests/Login.spec.ts test tests/Post-order.spec.ts test tests/TestWithApi.spec.ts test tests/PostApiLoanCalcDecision.spec.ts test tests/ApiLoop.spec.ts

